package GUIs;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import BaseClasses.Group;
import BaseClasses.Student;
import BaseClasses.SubjectClass;
import Database.DBEngine;
import java.io.File;
import java.util.ArrayList;

public class SendingReportInterface extends javax.swing.JFrame {
    
    private static String clName;
    private static String grID;
    private static String stID;
    
    public SendingReportInterface(String clName, String grID, String stID) {
        this.clName = clName;
        this.grID = grID;
        this.stID = stID;
        initComponents();
        showInformation();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnFirstSubmitting = new javax.swing.JButton();
        btnSecondSubmitting = new javax.swing.JButton();
        btnThirdSubmitting = new javax.swing.JButton();
        btnForthSubmitting = new javax.swing.JButton();
        btnFifthSubmitting = new javax.swing.JButton();
        jTextReport1 = new javax.swing.JTextField();
        jTextReport2 = new javax.swing.JTextField();
        jTextReport3 = new javax.swing.JTextField();
        jTextReport4 = new javax.swing.JTextField();
        jTextReport5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NỘP BÁO CÁO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NỘP BÁO CÁO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        btnFirstSubmitting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFirstSubmitting.setText("NỘP LẦN 1");
        btnFirstSubmitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstSubmittingActionPerformed(evt);
            }
        });

        btnSecondSubmitting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSecondSubmitting.setText("NỘP LẦN 2");
        btnSecondSubmitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondSubmittingActionPerformed(evt);
            }
        });

        btnThirdSubmitting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThirdSubmitting.setText("NỘP LẦN 3");
        btnThirdSubmitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirdSubmittingActionPerformed(evt);
            }
        });

        btnForthSubmitting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnForthSubmitting.setText("NỘP LẦN 4");
        btnForthSubmitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForthSubmittingActionPerformed(evt);
            }
        });

        btnFifthSubmitting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFifthSubmitting.setText("NỘP LẦN 5");
        btnFifthSubmitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFifthSubmittingActionPerformed(evt);
            }
        });

        jTextReport3.setToolTipText("");

        jTextReport5.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThirdSubmitting, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextReport3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnForthSubmitting, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextReport4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFifthSubmitting, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextReport5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFirstSubmitting, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSecondSubmitting, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jTextReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFirstSubmitting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextReport1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSecondSubmitting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextReport2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThirdSubmitting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextReport3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnForthSubmitting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextReport4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFifthSubmitting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextReport5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("NHÓM:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("LỚP:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/return.png"))); // NOI18N
        jButton1.setText("Quay về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(222, 222, 222)
                            .addComponent(jLabel3)
                            .addGap(38, 38, 38)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(214, 214, 214)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getClName(){
        return clName;
    }
    
    public static boolean writeObjectToFile(String fileName, String text) throws IOException {
        try {
            FileWriter fw = new FileWriter(fileName, true); // Mở file ở chế độ append
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter out = new PrintWriter(bw);
            
            out.println(text); // Ghi dữ liệu vào file

            out.close();
            bw.close();
            fw.close();
            
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }    
    
    private void showInformation() {
        try {
            ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
            for (SubjectClass cl : clList) {
                if (cl.getClName().equals(clName)) {
                    jLabel4.setText(clName);
                    for (Group gr : cl.getGrList()) {
                        if (gr.getGrID().equals(grID)) {
                            jLabel5.setText(grID);
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnFirstSubmittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstSubmittingActionPerformed
        // TODO add your handling code here:
        
        String text = jTextReport1.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng điền link báo cáo!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //tạo tên thư mục
            String folderName = "D:\\Data\\" + clName; //thư mục lớp 

            //tạo thư mục
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); // Tạo thư mục mới nếu chưa tồn tại
            }
        
            String fileName = folderName + "\\" + grID + "_Reoprt.txt"; //đường dẫn lưu báo cáo
        
        
            try {
                boolean success = writeObjectToFile(fileName, text);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Nộp thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Nộp thất bại");
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã có lỗi sảy ra");
            }
        }       
    }//GEN-LAST:event_btnFirstSubmittingActionPerformed

    private void btnSecondSubmittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondSubmittingActionPerformed
        // TODO add your handling code here:
        String text = jTextReport2.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng điền link báo cáo!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //tạo tên thư mục
            String folderName = "D:\\Data\\" + clName; //thư mục lớp 

            //tạo thư mục
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); // Tạo thư mục mới nếu chưa tồn tại
            }
        
            String fileName = folderName + "\\" + grID + "_Reoprt.txt"; //đường dẫn lưu báo cáo
        
        
            try {
                boolean success = writeObjectToFile(fileName, text);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Nộp thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Nộp thất bại");
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã có lỗi sảy ra");
            }
        }
    }//GEN-LAST:event_btnSecondSubmittingActionPerformed

    private void btnThirdSubmittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirdSubmittingActionPerformed
        // TODO add your handling code here:
        String text = jTextReport3.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng điền link báo cáo!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //tạo tên thư mục
            String folderName = "D:\\Data\\" + clName; //thư mục lớp 

            //tạo thư mục
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); // Tạo thư mục mới nếu chưa tồn tại
            }
        
            String fileName = folderName + "\\" + grID + "_Reoprt.txt"; //đường dẫn lưu báo cáo
        
        
            try {
                boolean success = writeObjectToFile(fileName, text);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Nộp thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Nộp thất bại");
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã có lỗi sảy ra");
            }
        }    
    }//GEN-LAST:event_btnThirdSubmittingActionPerformed

    private void btnForthSubmittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForthSubmittingActionPerformed
        // TODO add your handling code here:
        String text = jTextReport4.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng điền link báo cáo!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //tạo tên thư mục
            String folderName = "D:\\Data\\" + clName; //thư mục lớp 

            //tạo thư mục
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); // Tạo thư mục mới nếu chưa tồn tại
            }
        
            String fileName = folderName + "\\" + grID + "_Reoprt.txt"; //đường dẫn lưu báo cáo
        
        
            try {
                boolean success = writeObjectToFile(fileName, text);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Nộp thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Nộp thất bại");
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã có lỗi sảy ra");
            }
        }
    }//GEN-LAST:event_btnForthSubmittingActionPerformed

    private void btnFifthSubmittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFifthSubmittingActionPerformed
        // TODO add your handling code here:
        String text = jTextReport5.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng điền link báo cáo!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //tạo tên thư mục
            String folderName = "D:\\Data\\" + clName; //thư mục lớp 

            //tạo thư mục
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); // Tạo thư mục mới nếu chưa tồn tại
            }
        
            String fileName = folderName + "\\" + grID + "_Reoprt.txt"; //đường dẫn lưu báo cáo
        
        
            try {
                boolean success = writeObjectToFile(fileName, text);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Nộp thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Nộp thất bại");
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã có lỗi sảy ra");
            }
        }
    }//GEN-LAST:event_btnFifthSubmittingActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        int choice2 = JOptionPane.showConfirmDialog(this, "Bạn có muốn quay lại trang trước không?", "Thông báo!", JOptionPane.YES_NO_OPTION);
        if (choice2 == JOptionPane.YES_OPTION) {
            StudyManagementInterface student = new StudyManagementInterface();
            try {
                ArrayList<Student> stList = (ArrayList<Student>) DBEngine.readObjectFromFile("C:\\Database\\STUDENT.txt");
                for (Student st : stList) {
                    if (st.getStID().equals(stID)) {
                        student.setStID(st.getStID());
                        student.setStName(st.getStName());
                        student.setStGender(st.getStGender());
                        student.setStDepartment(st.getStDepartment());
                        student.setStClass(st.getStClass());
                        student.setStBatch(st.getStBatch());
                        student.setStPhoneNumber(st.getStPhoneNumber());
                    }
                }
                student.setVisible(true);
                this.setVisible(false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi database!");
            }
        }
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendingReportInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendingReportInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendingReportInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendingReportInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendingReportInterface(clName, grID, stID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFifthSubmitting;
    private javax.swing.JButton btnFirstSubmitting;
    private javax.swing.JButton btnForthSubmitting;
    private javax.swing.JButton btnSecondSubmitting;
    private javax.swing.JButton btnThirdSubmitting;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextReport1;
    private javax.swing.JTextField jTextReport2;
    private javax.swing.JTextField jTextReport3;
    private javax.swing.JTextField jTextReport4;
    private javax.swing.JTextField jTextReport5;
    // End of variables declaration//GEN-END:variables
}
