package GUIs;

import BaseClasses.Account;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;

public class TeachingManagementInterface extends javax.swing.JFrame {

    //properties
    private String tcID;
    private Account tcAccount;
    private String tcName;
    private String tcPhoneNumber;
    private String tcEmail;

    //setters
    public void setTcID(String tcID) {
        this.tcID = tcID;
    }

    public void setTcAccount(Account tcAccount) {
        this.tcAccount = tcAccount;
    }

    public void setTcName(String tcName) {
        this.tcName = tcName;
    }

    public void setTcPhoneNumber(String tcPhoneNumber) {
        this.tcPhoneNumber = tcPhoneNumber;
    }

    public void setTcEmail(String tcEmail) {
        this.tcEmail = tcEmail;
    }

    //constructor
    public TeachingManagementInterface() {
        initComponents();
        setLocationRelativeTo(null);
        setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTcID = new javax.swing.JLabel();
        lblTcIDDisplaying = new javax.swing.JLabel();
        lblTcName = new javax.swing.JLabel();
        lblTcNameDisplaying = new javax.swing.JLabel();
        lblTcPhoneNumber = new javax.swing.JLabel();
        lblTcPhoneNumberDisplaying = new javax.swing.JLabel();
        lblTcEmail = new javax.swing.JLabel();
        lblTcEmailDisplaying = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCreateGroup = new javax.swing.JButton();
        btnViewGroupList = new javax.swing.JButton();
        btnSignOut3 = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();
        btnViewClassList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GIAO DIỆN QUẢN LÝ GIẢNG DẠY");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/logo-ngang.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN GIẢNG VIÊN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        lblTcID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTcID.setText("MÃ GIẢNG VIÊN:");

        lblTcIDDisplaying.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblTcIDDisplaying.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTcIDDisplaying.setText("...");
        lblTcIDDisplaying.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblTcName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTcName.setText("TÊN GIẢNG VIÊN:");

        lblTcNameDisplaying.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblTcNameDisplaying.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTcNameDisplaying.setText("...");
        lblTcNameDisplaying.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblTcPhoneNumber.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTcPhoneNumber.setText("SỐ ĐIỆN THOẠI:");

        lblTcPhoneNumberDisplaying.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblTcPhoneNumberDisplaying.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTcPhoneNumberDisplaying.setText("...");
        lblTcPhoneNumberDisplaying.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblTcEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTcEmail.setText("EMAIL:");

        lblTcEmailDisplaying.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblTcEmailDisplaying.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTcEmailDisplaying.setText("...");
        lblTcEmailDisplaying.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnSignOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignOut.setText("ĐĂNG XUẤT");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTcID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTcName, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(lblTcPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTcEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTcIDDisplaying, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTcPhoneNumberDisplaying, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTcEmailDisplaying, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTcNameDisplaying, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTcID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTcIDDisplaying, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTcName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTcNameDisplaying, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTcPhoneNumberDisplaying, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTcEmailDisplaying, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTcPhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTcEmail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỨC NĂNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        btnCreateGroup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreateGroup.setText("TẠO NHÓM");
        btnCreateGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGroupListActionPerformed(evt);
            }
        });

        btnViewGroupList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewGroupList.setText("XEM DS NHÓM");
        btnViewGroupList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGroupListActionPerformed(evt);
            }
        });

        btnSignOut3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignOut3.setText("GỬI TÀI LIỆU");
        btnSignOut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendDocumentActionPerformed(evt);
            }
        });

        btnViewReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewReport.setText("XEM BÁO CÁO");
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });

        btnViewClassList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewClassList.setText("XEM DS LỚP");
        btnViewClassList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewClassListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewGroupList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignOut3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewClassList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(190, 190, 190))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btnViewClassList, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewGroupList, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "BẠN CHẮC CHẮN MUỐN ĐĂNG XUẤT?", "ĐĂNG XUẤT!", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new SigningInInterface().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblTcIDDisplaying.setText(tcID);
        lblTcNameDisplaying.setText(tcName);
        lblTcPhoneNumberDisplaying.setText(tcPhoneNumber);
        lblTcEmailDisplaying.setText(tcEmail);
    }//GEN-LAST:event_formWindowOpened

    private void btnCreateGroupListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGroupListActionPerformed
        new CreatingGroupInterface(lblTcIDDisplaying.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateGroupListActionPerformed

    private void btnViewGroupListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGroupListActionPerformed
        // TODO add your handling code here:
        new ViewingGroupListInterface(lblTcIDDisplaying.getText(), "").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewGroupListActionPerformed

    private void btnSendDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendDocumentActionPerformed
        // TODO add your handling code here:
        SendingDocumentInterface sentD = new SendingDocumentInterface();
        sentD.setTcID(tcID);
        sentD.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSendDocumentActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        // TODO add your handling code here:
        ViewingReportInterface reportInterface = new ViewingReportInterface("");
        reportInterface.setTcID(tcID);
        reportInterface.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewReportActionPerformed

    private void btnViewClassListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewClassListActionPerformed
        ViewingClassListInterface clInterface = new ViewingClassListInterface();
        clInterface.setTcID(tcID);
        clInterface.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewClassListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachingManagementInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachingManagementInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachingManagementInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachingManagementInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachingManagementInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateGroup;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSignOut3;
    private javax.swing.JButton btnViewClassList;
    private javax.swing.JButton btnViewGroupList;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblTcEmail;
    private javax.swing.JLabel lblTcEmailDisplaying;
    private javax.swing.JLabel lblTcID;
    private javax.swing.JLabel lblTcIDDisplaying;
    private javax.swing.JLabel lblTcName;
    private javax.swing.JLabel lblTcNameDisplaying;
    private javax.swing.JLabel lblTcPhoneNumber;
    private javax.swing.JLabel lblTcPhoneNumberDisplaying;
    // End of variables declaration//GEN-END:variables
}
