package GUIs;

import TableModels.ClassTableModel;
import BaseClasses.SubjectClass;
import Database.DBEngine;
import BaseClasses.Group;
import TableModels.GroupTableModel;
import Database.DBConnector;
import BaseClasses.Teacher;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class ViewingGroupListInterface extends javax.swing.JFrame {

    //properties
    private static String clName;
    private static String tcID;

    //constructors
    public ViewingGroupListInterface(String tcID, String className) {
        this.tcID = tcID;
        this.clName = className;
        initComponents();
        setLocationRelativeTo(null);
        setLayout(new FlowLayout());
        try {
            ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
            tblClassList.setModel(new ClassTableModel(clList));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể hiển thị dữ liệu do lỗi kết nối cơ sở dữ liệu!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void loadClassTable(ArrayList<SubjectClass> clList) {
        tblClassList.setModel(new ClassTableModel(clList));
    }

    public void loadGroupTable(ArrayList<Group> grList) {
        tblGroupList.setModel(new GroupTableModel(grList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        btnSearchClass = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassList = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        btnSearchGroup = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cboGroupFilter = new javax.swing.JComboBox<>();
        btnGroupFilter = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGroupList = new javax.swing.JTable();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GIAO DIỆN XEM DANH SÁCH NHÓM");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH NHÓM");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÌM LỚP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("TÊN LỚP:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnSearchClass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearchClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/search.png"))); // NOI18N
        btnSearchClass.setText("TÌM");
        btnSearchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchClass, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtClassName))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtClassName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỌN LỚP ĐỂ XEM DS NHÓM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblClassList.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblClassList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblClassList.getTableHeader().setReorderingAllowed(false);
        tblClassList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClassListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClassList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÌM NHÓM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("TÊN NHÓM:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnSearchGroup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearchGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/search.png"))); // NOI18N
        btnSearchGroup.setText("TÌM");
        btnSearchGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(btnSearchGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(43, 43, 43))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LỌC NHÓM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        cboGroupFilter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cboGroupFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa đánh giá", "Đã đánh giá" }));

        btnGroupFilter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGroupFilter.setText("LỌC");
        btnGroupFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboGroupFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(cboGroupFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGroupFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH NHÓM TRONG LỚP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblGroupList.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblGroupList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblGroupList.getTableHeader().setReorderingAllowed(false);
        tblGroupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGroupList);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/return.png"))); // NOI18N
        btnReturn.setText("QUAY VỀ");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReturn)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClassListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClassListMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblClassList.getSelectedRow();
        int columnIndex = 2;
        String value = (String) tblClassList.getValueAt(selectedRow, columnIndex);
        txtClassName.setText(value);
        clName = value;
        try {
            ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
            for (SubjectClass cl : clList) {
                if (cl.getClName().equals(value)) {
                    loadGroupTable(cl.getGrList());
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblClassListMouseClicked

    private void tblGroupListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupListMouseClicked
        // TODO add your handling code here:
        try {
            int selectedRow = tblGroupList.getSelectedRow();
            int columnIndex = 0;
            ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
            if (selectedRow != -1 && columnIndex != -1) {
                String value = (String) tblGroupList.getValueAt(selectedRow, columnIndex);
                for (SubjectClass cl : clList) {
                    if (cl.getClName().equals(clName)) {
                        for (Group gr : cl.getGrList()) {
                            if (gr.getGrID().equals(value)) {
                                new ViewingGroupInfoInterface(value, clName, tcID).setVisible(true);
                                this.setVisible(false);
                            }
                        }
                    }
                }
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblGroupListMouseClicked

    private void btnSearchGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGroupActionPerformed
        // TODO add your handling code here:
        if (!txtGroupName.getText().trim().equals("")) {
            try {
                ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
                ArrayList<Group> searchResults = new ArrayList<>();
                for (SubjectClass cl : clList) {
                    if (cl.getClName().equals(clName)) {
                        for (Group gr : cl.getGrList()) {
                            if (gr.getGrID().equals(txtGroupName.getText().trim())) {
                                searchResults.add(gr);
                            }
                        }
                    }
                }
                if (searchResults.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không có nhóm bạn cần tìm!", "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    loadGroupTable(searchResults);
                }
            } catch (Exception ex) {
                System.out.println(ex.toString());
                JOptionPane.showMessageDialog(this, "Lỗi!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên nhóm!", "Cảnh báo!", JOptionPane.WARNING_MESSAGE);
            txtGroupName.requestFocus();
        }
    }//GEN-LAST:event_btnSearchGroupActionPerformed

    private void btnGroupFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupFilterActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
            ArrayList<Group> filterResults = new ArrayList<>();
            if (cboGroupFilter.getSelectedItem().equals("Chưa đánh giá")) {
                for (SubjectClass cl : clList) {
                    if (cl.getClName().equals(clName)) {
                        for (Group gr : cl.getGrList()) {
                            if (gr.getGrEvaluation().equals("Chưa có đánh giá")) {
                                filterResults.add(gr);
                            }
                        }
                    }
                }
                loadGroupTable(filterResults);
            } else {
                for (SubjectClass cl : clList) {
                    if (cl.getClName().equals(clName)) {
                        for (Group gr : cl.getGrList()) {
                            if (!gr.getGrEvaluation().equals("Chưa có đánh giá")) {
                                filterResults.add(gr);
                            }
                        }
                    }
                }
                loadGroupTable(filterResults);
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGroupFilterActionPerformed

    private void btnSearchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClassActionPerformed
        // TODO add your handling code here:
        if (!txtClassName.getText().trim().equals("")) {
            try {
                ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
                ArrayList<SubjectClass> searchResults = new ArrayList<>();
                for (SubjectClass cl : clList) {
                    if (cl.getClName().equals(txtClassName.getText())) {
                        searchResults.add(cl);
                    }
                }
                if (searchResults.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không có nhóm bạn cần tìm!", "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    loadClassTable(searchResults);
                }
            } catch (Exception ex) {
                System.out.println(ex.toString());
                JOptionPane.showMessageDialog(this, "Lỗi!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên nhóm!", "Cảnh báo!", JOptionPane.WARNING_MESSAGE);
            txtGroupName.requestFocus();
        }
    }//GEN-LAST:event_btnSearchClassActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Quay về giao diện QUẢN LÝ GIẢNG DẠY?", "Quay về?", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            TeachingManagementInterface teacher = new TeachingManagementInterface();
            try {
                ArrayList<Teacher> tcList = (ArrayList<Teacher>) DBEngine.readObjectFromFile("C:\\Database\\TEACHER.txt");
                for (Teacher tc : tcList) {
                    if (tc.getTcID().equals(tcID)) {
                        teacher.setTcID(tcID);
                        teacher.setTcName(tc.getTcName());
                        teacher.setTcPhoneNumber(tc.getTcPhoneNumber());
                        teacher.setTcEmail(tc.getTcEmail());
                    }
                }
                teacher.setVisible(true);
                this.setVisible(false);
            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtClassName.setText(clName);
        if (!txtClassName.getText().trim().equals("")) {
            try {
                ArrayList<SubjectClass> clList = (ArrayList<SubjectClass>) DBEngine.readObjectFromFile("C:\\Database\\CLASSES.txt");
                for (SubjectClass cl : clList) {
                    if (cl.getClName().equals(txtClassName.getText())) {
                        loadGroupTable(cl.getGrList());
                    }
                }
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewingGroupListInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewingGroupListInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewingGroupListInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewingGroupListInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewingGroupListInterface(tcID, clName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGroupFilter;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearchClass;
    private javax.swing.JButton btnSearchGroup;
    private javax.swing.JComboBox<String> cboGroupFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClassList;
    private javax.swing.JTable tblGroupList;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtGroupName;
    // End of variables declaration//GEN-END:variables
}
